#########################################
# .cshrc file for HAWK system
#########################################

if ( $?prompt ) then
  set prompt = "`hostname`:\!>"
  set autoexpand
  set autolist
  set cdpath = ( ~ )
  set pushdtohome
endif

unset autologout
set autologout=0

umask 002
setenv TAPE /dev/st0
setenv PRINTER color.gate.rtf

# Set the build environment

setenv LANG C

setenv HOST_OS LINUX_NRIT
setenv LROSE_CORE_DIR $HOME/git/lrose-core
setenv LROSE_INSTALL_DIR $HOME/lrose
setenv RAP_MAKE_INC_DIR $HOME/git/lrose-core/codebase/make_include
setenv RAP_MAKE_BIN_DIR $HOME/git/lrose-core/codebase/make_bin
setenv RAP_INC_DIR $LROSE_INSTALL_DIR/include
setenv RAP_LIB_DIR $LROSE_INSTALL_DIR/lib
setenv RAP_BIN_DIR $LROSE_INSTALL_DIR/bin
setenv RAP_MAN_DIR $LROSE_INSTALL_DIR/man
setenv RAP_DOC_DIR $LROSE_INSTALL_DIR/doc
setenv RAP_SHARED_INC_DIR $LROSE_INSTALL_DIR/include
setenv RAP_SHARED_LIB_DIR $LROSE_INSTALL_DIR/lib
setenv RAP_SHARED_BIN_DIR $LROSE_INSTALL_DIR/bin

setenv SYS_LDFLAGS -L/usr/lib/x86_64-linux-gnu/hdf5/serial


# local build envars for packages installed under /nrit/ral

#setenv MY_ZLIB_INCS
#setenv MY_SZIP_INCS
#setenv MY_UDUNITS_INCS
#setenv MY_HDF5_INCS 
#setenv MY_NETCDF4_INCS

#setenv MY_ZLIB_LIBS
#setenv MY_SZIP_LIBS
#setenv MY_UDUNITS_LIBS
#setenv MY_HDF5_LIBS
#setenv MY_NETCDF4_LIBS


# CVS

setenv CVSUSER dixon
setenv CVSROOT :pserver:${CVSUSER}@localhost:/cvs

# --- OTHER BUILD SETTINGS

setenv FC gfortran
setenv GCC_WARNINGS -Wall

# --- LD run path --

#setenv LD_RUN_PATH $QTDIR/lib:/usr/local/lib:/usr/local/netcdf4/lib:
#setenv LD_LIBRARY_PATH /usr/local/lib

# --- JAVA ---

setenv JAVA_HOME /usr/java/latest
setenv ANT_HOME /usr/local/ant

# --- RUNTIME ---

setenv DATA_HOST localhost
setenv PROJ_DIR $HOME/projDir
setenv TITAN_HOME $PROJ_DIR
setenv DATA_DIR $PROJ_DIR/data
setenv RAP_DATA_DIR $DATA_DIR
setenv TMP_DIR $DATA_DIR/tmp
setenv LOG_DIR $DATA_DIR/logs
setenv DATA_DISTRIB_LOG_DIR $LOG_DIR/distrib
setenv ERRORS_LOG_DIR $LOG_DIR/errors
setenv RESTART_LOG_DIR $LOG_DIR/restart

setenv PROCMAP_HOST localhost
setenv DATA_MAPPER_ACTIVE true
setenv LDATA_FMQ_ACTIVE true

setenv DS_COMM_TIMEOUT_MSECS 60000
setenv DS_PING_TIMEOUT_MSECS 20000

setenv PAPER_SIZE 500x700+60+60

# --- site info --- 

if (-f $PROJ_DIR/system/params/site_info) then
  source $PROJ_DIR/system/params/site_info
endif

# --- Path ---

# Assemble path to include all scripts directories
# then projDir/bin, then the rest

set path = (.)
if ( -d $PROJ_DIR ) then
  foreach dir ($PROJ_DIR/*)
    if (-d $dir/scripts) then
      set path = ($path $dir/scripts)
    endif
  end
endif

if ($?LROSE_INSTALL_DIR) then
  if ( -d $LROSE_INSTALL_DIR/bin ) then
    set path = ($path $LROSE_INSTALL_DIR/bin)
  endif
endif

set savehist=0

set path = ($path ~/bin \
        /opt/local/bin \
	$JAVA_HOME/bin $ANT_HOME/bin \
	/usr/local/xpol \
	/usr/local/bin /usr/local/sbin /usr/bin/X11 \
        /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin \
	/opt/gfortran/irun/bin /opt/spol/bin \
        /usr/sigmet/bin /usr/sigmet/bin/rda  )

# -- core files --
# unlimit coredumpsize

# --- Aliases ---

if ($?prompt) then

  alias sc source ~/.cshrc

  alias matlab /usr/local/MATLAB/R2011a/bin/matlab

  alias setprompt 'set prompt="(`hostname`) `basename $cwd` ! % "'
  alias cd 'cd \!*;setprompt; echo $cwd'
  alias push 'pushd \!*; cd .'
  alias pop 'popd; cd .'

  set prompt = "%m:%~%# "             # tcsh
  set showdots                        # tcsh
  set watch = (1 root any)            # tcsh
  set history=1000
  set nobeep
  set time = 5

  setenv EDITOR emacs
  setenv PAGER less
  setenv LESS "-cMe"
  setenv LESSOPEN "|lesspipe.sh %s"
  setenv LESSCHARSET latin1

  alias h history
  alias ssh 'ssh -X'

  alias rm 'rm -i'
  alias mv 'mv -i'
  alias cp 'cp -i' 

  alias df 'df -h'
  set filec
  set fignore = (.o .ln)

  alias gstat 'git status'
  alias gcom 'git commit -am \!*'
  alias gpush 'git push'
  alias gpull 'git pull --ff-only'
  alias gdiff 'git diff '
  alias gdt 'git difftool -g -y '
  alias glol 'git log --graph --decorate --pretty=oneline --abbrev-commit --all'

  alias catw 'cat `which \!*`'
  alias lessw 'less `which \!*`'
  alias emacsw 'emacs -nw `which \!*`'
  alias viw 'vi `which \!*`'

  alias lst 'ls -l \!* | awk \{s+=\$4\}END\{print\ s\}'
  alias la 'ls -la --color=tty'
  alias ll 'ls -l --color=tty'
  alias lt 'ls -lt --color=tty'
  alias lat 'ls -alt --color=tty'
  alias l 'ls -sF'
  alias L ls -agl
  alias LS ls -aFRts 

  alias xx 'xrdb ~/.Xdefaults'
  alias cvs 'cvs -d :pserver:${CVSUSER}@localhost:/cvs \!*'
  alias cvsforward 'ssh -a -x -C -R 2401:localhost:2401'
  alias drx 'ssh -a -XY -C -R 2401:localhost:2401 radarop@192.168.85.78'
  alias xpol 'ssh -a -XY -C radarop@192.168.85.1'

  alias cvsmms 'ssh -a -x -C -Y -R 2401:localhost:2401 titan@202.21.178.204'
  alias cvsin 'ssh -a -x -C -L 2401:cvs:2401'
  alias cvsout 'ssh -a -x -C -R 2401:cvs:2401'
  
  alias gitstat 'git status -uno'

  alias gate 'ssh -a -XY -C -L 2401:cvs.rap.ucar.edu:2401 -L 8888:svn.eol.ucar.edu:80 dixon@gate.ucar.edu'

  alias psg 'ps axww | sed -n "1p; \|sed .*/\!*/|d; /\!*/p"'
  alias pslg 'ps alxww | sed -n "1p; \|sed .*/\!*/|d; /\!*/p"'
  alias psug 'ps auxww | sed -n "1p; \|sed .*/\!*/|d; /\!*/p"'
  alias psx 'ps xww | grep -v LogFilter'
  alias ensc 'enscript -2r -fCourier7'

  alias print_procmap 'print_procmap -hb -up -status'
  alias PrintDataMap 'PrintDataMap -all -relt -lreg'
  alias ppm 'print_procmap -hb -up -status'
  alias pdm 'PrintDataMap -all -relt -lreg'
  alias dmd 'DataMapper -delete '
  alias pcheck 'procmap_list_check -proc_list $PROJ_DIR/control/proc_list'
  alias dcheck 'DataMapper_list_check -data_list $PROJ_DIR/control/data_list'
  alias pcheckOK 'pcheck -ok'
  alias dcheckOK 'dcheck -ok'
  alias ph 'get_host_type'
  alias pgen_data 'cd /scr/pgen'
  alias pgen1_data 'cd /scr/pgen1'
  alias pgen2_data 'cd /scr/pgen2'

# save to dvd

  alias savedvd 'growisofs -Z /dev/dvd -r -J'
  alias saveiso2dvd 'growisofs -dvd-compat -Z /dev/dvd='

#    eval `dircolors ~/.dircolors`      # Set up color-ls variables.

# ssh command for drx

  alias drx 'ssh -XY  drx'

  setprompt

endif

